# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12-browsers

    steps:
      - checkout

      - restore_cache:
          #note: we are not currently version controlling yarn.lock so the cache restore will not work
          #TODO: enable for production builds
          name: Restore core JS dependencies cache
          keys:
            - v1-js-dependencies-{{ checksum "yarn.lock" }}
            # uncomment to allow fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
          paths:
            - ~/.cache/yarn

      - run:
          name: Install JS dependencies
          command: yarn install

      - save_cache:
          name: Cache core JS dependencies
          key: v1-js-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Compile CSS
          command: node_modules/sass/sass.js src/sass/main.scss src/main.css

      - run:
          name: Run Frontend tests
          command: yarn test --updateSnapshot --ci
          # use this line instead if we version control snapshots
          # command: yarn test --ci
