# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:7.10

#       # Specify service dependencies here if necessary
#       # CircleCI maintains a library of pre-built images
#       # documented at https://circleci.com/docs/2.0/circleci-images/
#       # - image: circleci/mongo:3.4.4

#     working_directory: ~/repo

#     steps:
#       - checkout

#       # Download and cache dependencies
#       - restore_cache:
#           keys:
#           - v1-dependencies-{{ checksum "package.json" }}
#           # fallback to using the latest cache if no exact match is found
#           - v1-dependencies-

#       - run: yarn install

#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}

#       # run tests!
#       - run: yarn test
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12-browsers
      - image: circleci/ruby:2.5.3-node-browsers
    steps:
      - checkout

      - run:
          name: ruby-sass
          command: gem install sass

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: yarn-install
          command: yarn install

      - run:
          name: yarn-sass
          command: sass src/sass/main.scss src/main.css

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: yarn-test-ci
          command: yarn test --ci
